#!/bin/sh
set -eu

handle() {
  local file file_orig

  file="$1"; shift
  file_orig="$file.original"

  dpkg-divert --package gsd-lcdfilter --add --rename \
    --divert "$file_orig" "$file"
}

if [ "$1" != upgrade ] || dpkg --compare-versions "$2" lt '2~'; then
  for f in '/usr/lib/gnome-settings-daemon-2.0/libxsettings.so' \
           '/usr/lib/gnome-settings-daemon-3.0/libxsettings.so'
  do
    handle "$f"
  done
fi

#DEBHELPER#

# vim:set et sw=2 sts=2:
